### PR TITLE
 bug fix about input sentences in synthesis time

### PR DESCRIPTION
**Pull request by Yeongtae**
bug fix about input sentences

### CODE REVIEW

**Comment by m-toman** [comment]
Thank you for the PR.
I don't really see why there is a difference in the path in map.txt whether "sentences" are load from file or not - in both cases "sentences" just holds a list of strings.
Why is this
https://github.com/m-toman/tacorn/pull/7/files#diff-e708a1edee0341db7024711a45e66550R63
necessary?

**Comment by Yeongtae** [comment]
When we generate a wave file after generating n wave files, 
old version generate 8 wave file.

**Comment by m-toman** [comment]
You are right that this should be fixed.

But why do we need to do
`os.path.join(args.mels_dir, m)`
to load the mels in case the sentences come from an input file and just
`m`
when not?

**Comment by Yeongtae** [comment]
You are right.
When I implement it, I had some mistake.

So I fixed it.

**Pull request merged**
